[package]
name = "oxide-desktop"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0"

[dependencies]
bitflags = "2.2.1"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

[dependencies.smithay]
git = "https://github.com/Smithay/smithay"
rev = "e3d461a057ba244d213a8498ec372b0799cca103"
default-features = false
features = ["backend_winit", "wayland_frontend", "desktop"]
